{
  [
    'example.erl',
    'example_2.erl'
  ],
  [
    verbose,
    warn_missing_spec,
    debug_info,
    {i,      "../_build/record_info/include"},
    {outdir, "../_build/examples/ebin"}
  ]
}.
